FilmScraper/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('app.urls', namespace='film') ),
    path('admin/', admin.site.urls),
]

app/urls.py
from django.conf.urls import url
from . import views

app_name = 'film'
urlpatterns = [
    url(r'^$', views.Home, name='home'),
    url(r'^search/$', views.FilmDetails, name='film_details'),
]

app/models.py
from django.db import models
from django.shortcuts import reverse


# Create your models here.
class FilmInformation(models.Model):
    ''' This Table contain Film Information in FilmInformationorary
    in other words data is not trusted it might be wrong '''

        ## film info
    name     = models.CharField(max_length=70)
    year     = models.CharField(max_length=4)
        ## all next can be null
    mpaa     = models.CharField(blank=True, null=True, max_length=20)
    length   = models.CharField(blank=True, null=True, max_length=20)
    category = models.CharField(blank=True, null=True, max_length=60)
    poster   = models.URLField (blank=True, null=True, max_length=200) 
    trailer  = models.URLField (blank=True, null=True, max_length=200)
    brief_en = models.TextField(blank=True, null=True)
    brief_ar = models.TextField(blank=True, null=True)
    country  = models.CharField(blank=True, null=True, max_length=50)
    language = models.CharField(blank=True, null=True, max_length=50)
        ## saved as text json data
    rating   = models.TextField(blank=True, null=True)
    reviews  = models.TextField(blank=True, null=True)
    cast     = models.TextField(blank=True, null=True)
    torrent  = models.TextField(blank=True, null=True)
    download = models.TextField(blank=True, null=True)
    subtitle = models.TextField(blank=True, null=True)
    prizes_won = models.TextField(blank=True, null=True)
    prizes_nomenee = models.TextField(blank=True, null=True)

    ## data to help
    trust    = models.BooleanField(default= False)
    trusted  = models.IntegerField(default= 0)

    ## json
    json = models.TextField(null=True, blank=True)

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'FilmInformation'
        verbose_name_plural = 'FilmInformations'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("film", kwargs={"name": self.name})

app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist

from json import dumps, loads
from .scripts.scrape_film import Film

from .models import FilmInformation

# Create your views here.
def Home(request):
    return render(request, 'home.html', {})

def get_object(Class, **kwargs):
    try:
        return Class.objects.get(**kwargs)
    except ObjectDoesNotExist:
        return None

def FilmDetails(request):
    if request.method == 'POST':
        filmName = request.POST.get('q')
        if filmName:
            info = get_object(FilmInformation, name=filmName.title())
            if not info:
                f = Film(filmName)
                f.build()
                info = f.info
                info.pop('user-query')
                info.update({'json': dumps(info)})
                film = FilmInformation(**info)
                film.save()
            else:
                info = loads(info.json)
            return render(request, 'details.html', info)
            # return HttpResponse( dumps(info.__dict__), content_type='application/json' )
            # return HttpResponse(info.__dict__)
        return HttpResponse('no filmName')
    return HttpResponse('no post')
        

 

app/templates/details.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>This is Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'style.css' %}" />
    <!-- <script src="main.js"></script> -->
</head>
<body>
    
    <main>
        <header>
            <div id="logo"><span>M</span>ovies <span>S</span>craper </div>
            <div id="search">
                <form action="{% url 'film:film_details' %}" method="POST">
                    {% csrf_token %}
                    <input type="search" name="q"/>
                    <input type="submit" value="Search">
                </form>
            </div>
        </header>
        <!-- start basic data section
            section contain
                name
                year
                mpaa
                length
                poster
                category
        -->
        <section id="basic-data">
            <div class="poster">
                <img src="{{poster}}" alt="poster of filmName">
            </div>

            <div class="text-data">
                <div class="header">
                    <div class="name">
                        <h3>{{name}} <span>({{year}})</span>.</h3>
                    </div>
                    <div class="sub-data">
                        <div class="mpaa">{{mpaa}}</div>
                        <div class="length">{{length}}</div>
                        <div class="category">
                            {% for cat in category %} 
                            <span>{{cat}}</span>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="extra-data">
                    <div>country: {{country| join:', '}}</div>
                    <div>language: {{language| join:', '}}</div>
                    <div>rating:
                        {% for site, rate in rating.items %}
                        <div class="sub-data" style="margin-left: 10px;">
                            <span>{{site}}</span>
                            <span>{{rate.rating}}/10</span>
                            <span>{{rate.count}}</span>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
        <!-- end basic data section -->

        <!-- start brief & trailer section -->
        <section id="brief">
            <div class="header">
                <h3>{{name}} (brief)</h3>
            </div>

            <div class="content">
                <div class="text-data">
                    {% if brief_ar %}
                    arab
                    {{brief_ar}}
                    {% else %}
                    english
                    {{brief_en}}
                    {% endif %}
                </div>
                <div class="trailer">
                    <video poster="{{trailer.img_src}}" preload="none" loop controls>
                        <source src="{{trailer.video_src}}" type="video/mp4">
                        <img src="{{trailer.img_src}}" />
                        <p>Your browser doesn't support HTML5 video. Here is a <a href="myVideo.mp4">link to the video</a> instead.</p>
                    </video>
                    <p>imdb: <a href="{{trailer.link}}" target="_blank">Trailer Video on imdb</a></p>
                </div>
            </div>
        </section>
        <!-- end brief section -->

        <!-- start cast section -->
        <section id="cast">
            <div class="header">
                <h3>Cast</h3>
            </div>

            <div class="content">
                {% for p in cast %}
                <div>
                    <img src="{{p.photo}}" alt="{{p.name}}">
                    <div>
                        <div class="name">
                            <a href="{{p.imdb_link}}">{{p.name}}</a>
                        </div>
                        <div class="role">{{p.chracter}}</div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </section>
        <!-- end cast section -->

        <!-- start download section -->
        <section id="download">
            <div class="header">
                <h3>Download</h3>
            </div>
            <div class="tabs">
                <span>Download</span>
                <span>Torrent</span>
                <span>Subtitle</span>
            </div>

            <div class="download-data">
                {% for site, data in download.items %}
                <br>
                <hr>
                {% for link, text in data.zipped %}
                  <hr>
                <div class="flex-box">
                    <div class="name">
                        <a href="{{link}}" target="_blank">{{site}}</a>
                    </div>
                    <div class="description">
                        {{text}}
                    </div>
                    <!-- <div class="qualities">
                        480p, 720p, 1080p
                    </div>
                    <div class="sizes">
                        316mb, 700mb, 1.1gb
                    </div>
                    <div class="quality">
                        bluray
                    </div> -->
                </div>
                {% endfor %}
                {% endfor %}
            </div>
            <div class="torrent-data">
                
            </div>
            <div class="subtitle-data">
                
            </div>
        </section>
        <!-- end download section -->
    </main>
</body>
</html>

app/templates/home.html
{% load static %}

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>This is Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'style.css' %}" />
    <!-- <script src="main.js"></script> -->
</head>
<main>
    <header>
        <div id="logo"><span>M</span>ovies <span>S</span>craper </div>
        <div id="search">
            <form action="{% url 'film:film_details' %}" method="POST">
                {% csrf_token %}
                <input type="search" name="q"/>
                <input type="submit" value="Search">
            </form>
        </div>
    </header>
</main>